### PR TITLE
Plotting Examples, Export some functionality to pyrolite

### PR DESCRIPTION
**Pull request by morganjwilliams**
The example plots have been updated and are using the python client to grab data directly from Earthchem. This also exports some functionality to a module I'm currently developing. 

For the moment, it'll provide:
* basic spider plots, 
* ternary plots (to be improved/refactored) and 
* density plots (including on ternary diagrams, to some degree)

I've added a simple function to reformat dataframes generated directly from queries (`earthchem.formatting.cleanup_dataframe`) - I'd suggest you use something like this by default when using the `Query.dataframe` method.

### CODE REVIEW

**Comment by jesserobertson** [comment]
Hey looking at the travis output it looks like it's complaining about your format string (which is a python 3.6-only innovation btw)

Relevant test output:
```
E     File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pyrolite-0.0.7-py3.5.egg/pyrolite/plot.py", line 96
E       warnings.warn(f'Styling not yet implemented for:{unused_keys}')
E                                                                    ^
E   SyntaxError: invalid syntax
```

Secondly - I think it's worth keeping plotting functionality seperate in pyrolite and removing earthchem.plots. I'd just add some readme stuff that adds pyrolite as an optional plotting module. We can do that with a conditional import in the package.

**Comment by jesserobertson** [comment]
@morganjwilliams do you have access to the travis for this? It _should_ just be public

**Comment by morganjwilliams** [comment]
The travis is public, yes. I've updated pyrolite for 3.5 compatibility ([travis here](https://travis-ci.org/morganjwilliams/pyrolite/builds/398967795)) since I put this pull request through, so the build test should now pass here also. I agree that it'll be simpler to remove earthchem.plots.

**Comment by jesserobertson** [comment]
Goodo so you want to update this PR and see if it passes then?

**Pull request merged**
